export const encodings = {
    "4xm": "4X Movie",
    "flv": "FLV / Sorenson Spark / Sorenson H.263 (Flash Video) (codec flv1)",
    "mpegvideo": "MPEG-1 video (codec mpeg2video)",
    "tdsc": "TDSC",
    "8bps": "QuickTime 8BPS video",
    "fmvc": "FM Screen Capture Codec",
    "msa1": "MS ATC Screen",
    "theora": "Theora",
    "012v": "Uncompressed 4:2:2 10-bit",
    "fraps": "Fraps",
    "mscc": "Mandsoft Screen Capture Codec",
    "thp": "Nintendo Gamecube THP video",
    "aasc": "Autodesk RLE",
    "frwu": "Forward Uncompressed",
    "msmpeg4": "MPEG-4 part 2 Microsoft variant version 3 (codec msmpeg4v3)",
    "tiertexseqvideo": "Tiertex Limited SEQ video",
    "agm": "Amuse Graphics Movie",
    "g2m": "Go2Meeting",
    "msmpeg4v1": "MPEG-4 part 2 Microsoft variant version 1",
    "tiff": "TIFF image",
    "aic": "Apple Intermediate Codec",
    "gdv": "Gremlin Digital Video",
    "msmpeg4v2": "MPEG-4 part 2 Microsoft variant version 2",
    "tmv": "8088flex TMV",
    "alias_pix": "Alias/Wavefront PIX image",
    "gif": "GIF (Graphics Interchange Format)",
    "msrle": "Microsoft RLE",
    "truemotion1": "Duck TrueMotion 1.0",
    "amv": "AMV Video",
    "h261": "H.261",
    "mss1": "MS Screen 1",
    "truemotion2": "Duck TrueMotion 2.0",
    "anm": "Deluxe Paint Animation",
    "h263": "H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2",
    "mss2": "MS Windows Media Video V9 Screen",
    "truemotion2rt": "Duck TrueMotion 2.0 Real Time",
    "ansi": "ASCII/ANSI art",
    "h263i": "Intel H.263",
    "msvideo1": "Microsoft Video 1",
    "tscc2": "TechSmith Screen Codec 2",
    "apng": "APNG (Animated Portable Network Graphics) image",
    "h263p": "H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2",
    "mszh": "LCL (LossLess Codec Library) MSZH",
    "txd": "Renderware TXD (TeXture Dictionary) image",
    "arbc": "Gryphon's Anim Compressor",
    "h263_v4l2m2m": "V4L2 mem2mem H.263 decoder wrapper (codec h263)",
    "mts2": "MS Expression Encoder Screen",
    "ultimotion": "IBM UltiMotion (codec ulti)",
    "asv1": "ASUS V1",
    "h264": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
    "mv30": "MidiVid 3.0",
    "utvideo": "Ut Video",
    "asv2": "ASUS V2",
    "h264_cuvid": "Nvidia CUVID H264 decoder (codec h264)",
    "mvc1": "Silicon Graphics Motion Video Compressor 1",
    "v210": "Uncompressed 4:2:2 10-bit",
    "aura": "Auravision AURA",
    "h264_qsv": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration) (codec h264)",
    "mvc2": "Silicon Graphics Motion Video Compressor 2",
    "v210x": "Uncompressed 4:2:2 10-bit",
    "aura2": "Auravision Aura 2",
    "h264_v4l2m2m": "V4L2 mem2mem H.264 decoder wrapper (codec h264)",
    "mvdv": "MidiVid VQ",
    "v308": "Uncompressed packed 4:4:4",
    "avrn": "Avid AVI Codec",
    "hap": "Vidvox Hap",
    "mvha": "MidiVid Archive Codec",
    "v408": "Uncompressed packed QT 4:4:4:4",
    "avrp": "Avid 1:1 10-bit RGB Packer",
    "hevc": "HEVC (High Efficiency Video Coding)",
    "mwsc": "MatchWare Screen Capture Codec",
    "v410": "Uncompressed 4:4:4 10-bit",
    "avs": "AVS (Audio Video Standard) video",
    "hevc_cuvid": "Nvidia CUVID HEVC decoder (codec hevc)",
    "mxpeg": "Mobotix MxPEG video",
    "vb": "Beam Software VB",
    "avui": "Avid Meridien Uncompressed",
    "hevc_qsv": "HEVC (Intel Quick Sync Video acceleration) (codec hevc)",
    "notchlc": "NotchLC",
    "vble": "VBLE Lossless Codec",
    "ayuv": "Uncompressed packed MS 4:4:4:4",
    "hevc_v4l2m2m": "V4L2 mem2mem HEVC decoder wrapper (codec hevc)",
    "nuv": "NuppelVideo/RTJPEG",
    "vc1": "SMPTE VC-1",
    "bethsoftvid": "Bethesda VID video",
    "hnm4video": "HNM 4 video",
    "paf_video": "Amazing Studio Packed Animation File Video",
    "vc1image": "Windows Media Video 9 Image v2",
    "bfi": "Brute Force & Ignorance",
    "hqx": "Canopus HQX",
    "pam": "PAM (Portable AnyMap) image",
    "vc1_cuvid": "Nvidia CUVID VC1 decoder (codec vc1)",
    "binkvideo": "Bink video",
    "hq_hqa": "Canopus HQ/HQA",
    "pbm": "PBM (Portable BitMap) image",
    "vc1_qsv": "VC-1 video (Intel Quick Sync Video acceleration) (codec vc1)",
    "bintext": "Binary text",
    "huffyuv": "Huffyuv / HuffYUV",
    "pcx": "PC Paintbrush PCX image",
    "vc1_v4l2m2m": "V4L2 mem2mem VC1 decoder wrapper (codec vc1)",
    "bitpacked": "Bitpacked",
    "hymt": "HuffYUV MT",
    "pfm": "PFM (Portable FloatMap) image",
    "vcr1": "ATI VCR1",
    "bmp": "BMP (Windows and OS/2 bitmap)",
    "idcinvideo": "id Quake II CIN video (codec idcin)",
    "pgm": "PGM (Portable GrayMap) image",
    "vmdvideo": "Sierra VMD video",
    "bmv_video": "Discworld II BMV video",
    "idf": "iCEDraw text",
    "pgmyuv": "PGMYUV (Portable GrayMap YUV) image",
    "vmnc": "VMware Screen Codec / VMware Video",
    "brender_pix": "BRender PIX image",
    "iff": "IFF ACBM/ANIM/DEEP/ILBM/PBM/RGB8/RGBN (codec iff_ilbm)",
    "pictor": "Pictor/PC Paint",
    "vp3": "On2 VP3",
    "c93": "Interplay C93",
    "imm4": "Infinity IMM4",
    "pixlet": "Apple Pixlet",
    "vp4": "On2 VP4",
    "camstudio": "CamStudio (codec cscd)",
    "imm5": "Infinity IMM5",
    "png": "PNG (Portable Network Graphics) image",
    "vp5": "On2 VP5",
    "camtasia": "TechSmith Screen Capture Codec (codec tscc)",
    "indeo2": "Intel Indeo 2",
    "ppm": "PPM (Portable PixelMap) image",
    "vp6": "On2 VP6",
    "cavs": "Chinese AVS (Audio Video Standard) (AVS1-P2, JiZhun profile)",
    "indeo3": "Intel Indeo 3",
    "prores": "ProRes (iCodec Pro)",
    "vp6a": "On2 VP6 (Flash version, with alpha channel)",
    "cdgraphics": "CD Graphics video",
    "indeo4": "Intel Indeo Video Interactive 4",
    "prosumer": "Brooktree ProSumer Video",
    "vp6f": "On2 VP6 (Flash version)",
    "cdtoons": "CDToons video",
    "indeo5": "Intel Indeo Video Interactive 5",
    "psd": "Photoshop PSD file",
    "vp7": "On2 VP7",
    "cdxl": "Commodore CDXL video",
    "interplayvideo": "Interplay MVE video",
    "ptx": "V.Flash PTX image",
    "vp8": "On2 VP8",
    "cfhd": "Cineform HD",
    "jpeg2000": "JPEG 2000",
    "qdraw": "Apple QuickDraw",
    "vp8_cuvid": "Nvidia CUVID VP8 decoder (codec vp8)",
    "cinepak": "Cinepak",
    "jpegls": "JPEG-LS",
    "qpeg": "Q-team QPEG",
    "vp8_qsv": "VP8 video (Intel Quick Sync Video acceleration) (codec vp8)",
    "clearvideo": "Iterated Systems ClearVideo",
    "jv": "Bitmap Brothers JV video",
    "qtrle": "QuickTime Animation (RLE) video",
    "vp8_v4l2m2m": "V4L2 mem2mem VP8 decoder wrapper (codec vp8)",
    "cljr": "Cirrus Logic AccuPak",
    "kgv1": "Kega Game Video",
    "r10k": "AJA Kona 10-bit RGB Codec",
    "vp9": "Google VP9",
    "cllc": "Canopus Lossless Codec",
    "kmvc": "Karl Morton's video codec",
    "r210": "Uncompressed RGB 10-bit",
    "vp9_cuvid": "Nvidia CUVID VP9 decoder (codec vp9)",
    "copy": "Stream copy",
    "lagarith": "Lagarith lossless",
    "rasc": "RemotelyAnywhere Screen Capture",
    "vp9_qsv": "VP9 video (Intel Quick Sync Video acceleration) (codec vp9)",
    "cpia": "CPiA video format",
    "libaom-v1": "libaom AV1 (codec av1)",
    "rawvideo": "raw video",
    "vp9_v4l2m2m": "V4L2 mem2mem VP9 decoder wrapper (codec vp9)",
    "cyuv": "Creative YUV (CYUV)",
    "libdav1d": "dav1d AV1 decoder by VideoLAN (codec av1)",
    "rl2": "RL2 video",
    "vqavideo": "Westwood Studios VQA (Vector Quantized Animation) video (codec ws_vqa)",
    "dds": "DirectDraw Surface image decoder",
    "libopenjpeg": "OpenJPEG JPEG 2000 (codec jpeg2000)",
    "roqvideo": "id RoQ video (codec roq)",
    "wcmv": "WinCAM Motion Video",
    "dfa": "Chronomaster DFA",
    "libvpx": "libvpx VP8 (codec vp8)",
    "rpza": "QuickTime video (RPZA)",
    "webp": "WebP image",
    "dirac": "BBC Dirac VC-2",
    "libvpx": "p9                                                                      (libvpx VP9 (codec vp9)",
    "rscc": "innoHeim/Rsupport Screen Capture Codec",
    "wmv1": "Windows Media Video 7",
    "dnxhd": "VC3/DNxHD",
    "loco": "LOCO",
    "rv10": "RealVideo 1.0",
    "wmv2": "Windows Media Video 8",
    "dpx": "DPX (Digital Picture Exchange) image",
    "lscr": "LEAD Screen Capture",
    "rv20": "RealVideo 2.0",
    "wmv3": "Windows Media Video 9",
    "dsicinvideo": "Delphine Software International CIN video",
    "m101": "Matrox Uncompressed SD",
    "rv30": "RealVideo 3.0",
    "wmv3image": "Windows Media Video 9 Image",
    "dvvideo": "DV (Digital Video)",
    "magicyuv": "MagicYUV video",
    "rv40": "RealVideo 4.0",
    "wnv1": "Winnov WNV1",
    "dxa": "Feeble Files/ScummVM DXA",
    "mdec": "Sony PlayStation MDEC (Motion DECoder)",
    "sanm": "LucasArts SANM/Smush video",
    "wrapped_avframe": "AVPacket to AVFrame passthrough",
    "dxtory": "Dxtory",
    "mimic": "Mimic",
    "scpr": "ScreenPressor",
    "xan_wc3": "Wing Commander III / Xan",
    "dxv": "Resolume DXV",
    "mjpeg": "MJPEG (Motion JPEG)",
    "screenpresso": "Screenpresso",
    "xan_wc4": "Wing Commander IV / Xxan",
    "eacmv": "Electronic Arts CMV video (codec cmv)",
    "mjpegb": "Apple MJPEG-B",
    "sgi": "SGI image",
    "xbin": "eXtended BINary text",
    "eamad": "Electronic Arts Madcow Video (codec mad)",
    "mjpeg_cuvid": "Nvidia CUVID MJPEG decoder (codec mjpeg)",
    "sgirle": "Silicon Graphics RLE 8-bit video",
    "xbm": "XBM (X BitMap) image",
    "eatgq": "Electronic Arts TGQ video (codec tgq)",
    "mjpeg_qsv": "MJPEG video (Intel Quick Sync Video acceleration) (codec mjpeg)",
    "sheervideo": "BitJazz SheerVideo",
    "xface": "X-face image",
    "eatgv": "Electronic Arts TGV video (codec tgv)",
    "mmvideo": "American Laser Games MM Video",
    "smackvid": "Smacker video (codec smackvideo)",
    "xl": "Miro VideoXL (codec vixl)",
    "eatqi": "Electronic Arts TQI Video (codec tqi)",
    "motionpixels": "Motion Pixels video",
    "smc": "QuickTime Graphics (SMC)",
    "xpm": "XPM (X PixMap) image",
    "escape124": "Escape 124",
    "mpeg1video": "MPEG-1 video",
    "smvjpeg": "SMV JPEG",
    "xwd": "XWD (X Window Dump) image",
    "escape130": "Escape 130",
    "mpeg1_cuvid": "Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)",
    "snow": "Snow",
    "y41p": "Uncompressed YUV 4:1:1 12-bit",
    "exr": "OpenEXR image",
    "mpeg1_v4l2m2m": "V4L2 mem2mem MPEG1 decoder wrapper (codec mpeg1video)",
    "sp5x": "Sunplus JPEG (SP5X)",
    "ylc": "YUY2 Lossless Codec",
    "ffv1": "FFmpeg video codec #1",
    "mpeg2video": "MPEG-2 video",
    "speedhq": "NewTek SpeedHQ",
    "yop": "Psygnosis YOP Video",
    "ffvhuff": "Huffyuv FFmpeg variant",
    "mpeg2_cuvid": "Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)",
    "srgc": "Screen Recorder Gold Codec",
    "yuv4": "Uncompressed packed 4:2:0",
    "fic": "Mirillis FIC",
    "mpeg2_qsv": "MPEG-2 video (Intel Quick Sync Video acceleration) (codec mpeg2video)",
    "sunrast": "Sun Rasterfile image",
    "zerocodec": "ZeroCodec Lossless Video",
    "fits": "Flexible Image Transport System",
    "mpeg2_v4l2m2m": "V4L2 mem2mem MPEG2 decoder wrapper (codec mpeg2video)",
    "svq1": "Sorenson Vector Quantizer 1 / Sorenson Video 1 / SVQ1",
    "zlib": "LCL (LossLess Codec Library) ZLIB",
    "flashsv": "Flash Screen Video v1",
    "mpeg4": "MPEG-4 part 2",
    "svq3": "Sorenson Vector Quantizer 3 / Sorenson Video 3 / SVQ3",
    "zmbv": "Zip Motion Blocks Video",
    "flashsv2": "Flash Screen Video v2",
    "mpeg4_cuvid": "Nvidia CUVID MPEG4 decoder (codec mpeg4)",
    "targa": "Truevision Targa image",
    "flic": "Autodesk Animator Flic video",
    "mpeg4_v4l2m2m": "V4L2 mem2mem MPEG4 decoder wrapper (codec mpeg4)",
    "targa_y216": "Pinnacle TARGA CineWave YUV16"
}